### ISSUE TITLE
ブックマークアイコンをタップしても星マークが付かない時がある

### ISSUE THREAD

**Issue by chiemi627** [Tsukuba-SAY/PosMApp#10]
基本情報ウインドウからブックマークアイコンをタップしても星マークが付かない。
基本情報ウインドウを消すと星マークが現れる。

この現象は毎回起きるわけではなく、現時点で再現性がない。
https://github.com/Tsukuba-SAY/PosMApp/issues/9 が生じた後に起きる可能性が高い。

また、ラベルの種類を変更するとこの現象が起きなくなる。

**Comment by furuya-s** [comment]
Release 4 デモでは一度も報告されず、再現性も無いので、一度closeします。
