### ISSUE TITLE
ダブルタップをした時に地図が大きく外れるときがある

### ISSUE THREAD

**Issue by chiemi627** [Tsukuba-SAY/PosMApp#11]
https://github.com/Tsukuba-SAY/PosMApp/issues/9
が起きた後に必ず起きる現象です。

ダブルタップでマップの全面が見えるようにならず
大きく外れてしまうようになります。

**Comment by using923** [comment]
地図リセット機能をなくしたので回避していた

**Comment by furuya-s** [comment]
#9 が回避されているので回避済みです。
