### ISSUE TITLE
ポスターリストまたはブックマークリスト画面からあるポスターの詳細情報画面を表示し、ブラウザの戻るボタンをクリックすると、タブバーの強調表示が正しくない

### ISSUE THREAD

**Issue by Altaizym** [Tsukuba-SAY/PosMApp#33]

**Comment by furuya-s** [comment]
#23 と関連したissueです。
戻るボタンを抑制するかどうか検討する必要があります。

**Comment by Altaizym** [comment]
ブラウザの「戻る」、「進む」ボタンをクリックする時、popstate方法が呼び出されて、中に、event.state.hashの内容（「前のページ」と「後のページ」のアドレス）を監視してから、タブバーの強調表示切替操作を行います。

**Comment by using923** [comment]
Safariで動作せず

**Comment by using923** [comment]
以前から発生しているアクティブが消えるバグの影響でたまにアクティブ自体がずれることがあるが、正常に動作している場合はちゃんと動作することを確認。
