### ISSUE TITLE
ポスターリストでスクロール中にマップやトップ画面に遷移してしまう

### ISSUE THREAD

**Issue by BLThunder1991** [Tsukuba-SAY/PosMApp#34]
スクロールの起点でマップアイコンやタブバーなどに触れてしまうと画面に遷移してしまう用に感じる。

使う側からすると、スクロールしようとしているのに遷移してしまうのでストレスが溜まる。

**Comment by furuya-s** [comment]
要素をタップした時に発動するイベントを `touchstart` から `click` に変更することで回避しました。
9cc57a8e6b5a80b0193446095ea26a70a837f821 をご確認ください。
