### ISSUE TITLE
ポスターの場所に書いてある文字が小さい

### ISSUE THREAD

**Issue by m-oke** [Tsukuba-SAY/PosMApp#35]
端末:SH-07E
マップにおいて，ポスターの場所にチームID(SIT01とか)が書いてあるけども，デフォルトだと文字が小さくてとても見えない．
拡大すると見える．
部屋名や場所名(Coffee lounge等)は十分見える．

**Comment by furuya-s** [comment]
ポスターアイコンの幅に合わせることで修正しました。
