### ISSUE TITLE
ポスターアイコンのフラグがおかしい

### ISSUE THREAD

**Issue by furuya-s** [Tsukuba-SAY/PosMApp#75]
* 「Flickr」で検索
* エリアタップ
* 強調表示
* ×ボタンを押さずに、「Twitter」で検索
* 基本情報パネルを閉じる
* 検索に該当したままになっている！

**Comment by Altaizym** [comment]
検索キーワード変更の場合、前回強調表示かつタッチされたポスターの状態が普通のタッチ状態に戻るように修正しました。
