### ISSUE TITLE
P4セッションがなく、F4セッションとくっついている

### ISSUE THREAD

**Issue by furuya-s** [Tsukuba-SAY/PosMApp#76]

**Comment by using923** [comment]
2e6ed15ec6149bdda3c9d463260c9aaf3db677ce あたりで

![ss 2015-01-31 22 38 53](https://cloud.githubusercontent.com/assets/2645151/5988236/062a78e6-a99a-11e4-9a6d-1798c71723e2.png)

この通り直しました

**Comment by using923** [comment]
この修正にあたり、APIを直したのでdeletestorageしておいてほしいです
